export const SECTORS = [
  'Technology & Software',
  'FinTech & Financial Services',
  'BioTech & Life Sciences',
  'Healthcare',
  'Education & EdTech',
  'Entertainment & Media',
  'Hospitality & Tourism',
  'Retail & E-commerce',
  'Manufacturing & Engineering',
  'Energy & Environment',
  'Real Estate & Construction',
  'Logistics & Supply Chain',
  'Legal & Compliance',
  'Marketing & Advertising',
  'Consulting & Professional Services',
  'Staffing & Recruiting',
  'Non-profit & Social Impact',
  'Government & Public Sector',
] as const
